language: scala
scala:
  - 2.11.1
jdk:
  - oraclejdk8
addons:
    postgresql: "9.3"
before_script:
  - createuser -U postgres -s -d -r web
  - createdb -h localhost -U web api
  - git clone git://github.com/gilt/schema-evolution-manager.git
  - cd schema-evolution-manager
  - git checkout 0.9.12
  - ./configure.rb --lib_dir /usr/lib --bin_dir /usr/bin
  - sudo ./install.rb
  - cd ../schema
  - ./dev.rb
  - cd ..
script: sbt test
