language: scala
scala:
  - 2.11.5
jdk:
  - oraclejdk8
addons:
    postgresql: "9.3"
before_script:
  - createuser -U postgres -s -d -r web
  - createdb -h localhost -U web apidoc
  - git clone git://github.com/gilt/schema-evolution-manager.git
  - cd schema-evolution-manager
  - git checkout 0.9.16
  - cd ../schema
  - ../schema-evolution-manager/bin/sem-apply --host localhost --user web --name apidoc
  - cd ..

